### PR TITLE
Update to be compatible with Channels v3

### PR DESCRIPTION
**Pull request by tommcn**
ref: #1

### CODE REVIEW

**Comment by csdenboer** [comment]
Thanks for the PR! I have a few remarks that need to be fixed before I can merge this. Could you please have a look at them?
- A few tests are broken
- Code not formatted with black (https://github.com/psf/black)

**Comment by tommcn** [comment]
Hello, thank you for the feedback, could you look at it now?

**Comment by csdenboer** [comment]
Thanks for all the fixes! I haven’t tested, but I don’t think this change is compatible with Channels 2. Channnels 3 includes some breaking changes as described here: https://channels.readthedocs.io/en/stable/releases/3.0.0.html#update-to-asgi-3. Did you test it with Channels 2? If so, please add the different Channels versions to the travis config (like we do to test compatibility with different Python and Django versions).

**Comment by tommcn** [comment]
Yeah, you're right, I messed up running tox. Im sorry for the confusion.

**Pull request merged**
